### ISSUE TITLE
Implement Redeem

### ISSUE THREAD

**Issue by drtex0** [Atbash-Protocol/v1-frontend#27]
## Redeem 

Based on the https://github.com/SnowbankDAO/snowbank-frontend implement the Redeem.

### Tasks
- [] Create a new View Redeem
- [] Enhance the bond slice to implement the redeem thunks
- [] Implement the Redeem using BondDialog component
